import {
  IManualPayment,
  IReceivableResponse,
  MethodEnum,
  PaymentStatusEnum,
} from '@/domain/aggregates/order'
import ISearch from '@/domain/seedWork/paging/ISearch'

export const mockOrdersResponse: ISearch<IReceivableResponse> = {
  data: [
    {
      id: '1',
      referenceId: 'ref-1',
      subReferenceId: 'sub-ref-1',
      conditionId: 'cond-1',
      systemId: 1,
      adminLink: 'admin-link',
      discounts: [
        {
          id: 'disc-1',
          createdAt: '2023-01-01T00:00:00Z',
          oldAmount: 10,
          oldDiscount: 20,
          requestAmount: 30,
          requestDiscount: 40,
          requester: {
            id: 'req-id',
            email: 'req-email',
            name: 'req-name',
          },
          systemId: 1,
        },
      ],
      refunds: [],
      businessPartner: {
        id: 'bp-1',
        firstName: 'John',
        lastName: 'Doe',
        name: 'John Doe',
        email: 'john@example.com',
        documentType: 'CPF',
        documentNumber: '12345678900',
        phoneNumber: '11999999999',
        address: {
          street: 'Rua Teste',
          number: '123',
          complement: 'Apto 1',
          neighborhood: 'Centro',
          city: 'São Paulo',
          state: 'SP',
          postalCode: '01001000',
        },
      },
      status: 'PENDING',
      company: { id: 1, description: 'MULTI', code: 'MULTI' },
      amount: 100.5,
      discount: 10.0,
      expirationTime: 30,
      callbackUrl: 'http://callback.com',
      paymentLink: 'http://payment.com',
      updatedAt: '2023-01-01T00:00:00Z',
      createdAt: '2023-01-01T00:00:00Z',
      paymentMethods: ['CREDIT_CARD'],
      requester: {
        id: 'req-1',
        name: 'Requester 1',
        email: 'requester1@email.com',
      },
      items: [
        {
          id: 'item-1',
          name: 'Item 1',
          quantity: 1,
          image: process.env.NEXT_PUBLIC_NO_IMAGE!,
          unitPrice: 100.5,
        },
      ],
      payments: [
        {
          id: 'pay-1',
          method: MethodEnum.CREDIT_CARD,
          amount: 100.5,
          status: PaymentStatusEnum.CONFIRMED,
          createdAt: '2023-01-01T00:00:00Z',
          updatedAt: '2023-01-01T00:00:00Z',
          authorizedAt: '2023-01-01T00:00:00Z',
          companyId: 1,
          approvedAt: '2023-01-01T00:00:00Z',
          internalPaymentId: 'interpay-1',
          acquirer: {
            id: 1,
            ec: '123',
            description: 'Getnet',
            paymentId: 'pay-1',
            status: 'pending',
            statusDetail: 'waiting',
            nsu: '123456',
            transactionId: 'trans-123',
            internalPaymentId: 'interpay-1',
            authorizationCode: 'auth-123',
          },
        },
      ],
    },
  ],
  paging: {
    currentPage: 1,
    perPage: 10,
    total: 1,
    pages: 1,
  },
}

export const manualPaymentsMock: IManualPayment[] = [
  {
    id: 'mp-001',
    amount: 1500.75,
    reason: 'Pagamento manual referente a ajuste de fatura',
    attachments: ['https://example.com/attachments/comprovante-001.pdf'],
    createdAt: '2025-01-05T14:30:00Z',
    updatedAt: '2025-01-05T15:10:00Z',
    requester: {
      id: 'req-001',
      name: 'João Silva',
      email: 'joao.silva@example.com',
    },
    acquirer: {
      id: 1,
      ec: 'EC123456',
      description: 'Adquirente principal',
      paymentId: 'pay-001',
      status: 'approved',
      statusDetail: 'Pagamento aprovado com sucesso',
      nsu: '123456789',
      transactionId: 'trx-001',
      internalPaymentId: 'int-pay-001',
      authorizationCode: 'AUTH1234',
    },
  },
  {
    id: 'mp-002',
    amount: 320.0,
    reason: 'Pagamento manual por cobrança extraordinária',
    attachments: ['https://example.com/attachments/comprovante-002.jpg'],
    createdAt: '2025-01-04T10:00:00Z',
    updatedAt: '2025-01-04T10:45:00Z',
    requester: {
      id: 'req-002',
      name: 'Maria Oliveira',
      email: 'maria.oliveira@example.com',
    },
    acquirer: {
      id: 1,
      ec: 'EC987654',
      description: 'Adquirente secundário',
      paymentId: 'pay-002',
      status: 'pending',
      statusDetail: 'Aguardando confirmação do banco emissor',
      nsu: '987654321',
      transactionId: 'trx-002',
      internalPaymentId: 'int-pay-002',
      authorizationCode: 'AUTH5678',
    },
  },
]

export const mockOrder: IReceivableResponse = mockOrdersResponse.data[0]
