export const systemsOptions = [
  { value: 1, label: 'MERCURY' },
  { value: 2, label: 'GARANTIA ONLINE' },
  { value: 3, label: 'GARANTIA ONLINE ANTIGO' },
  { value: 4, label: 'LOJA GARANTIA' },
  { value: 5, label: 'MARKETPLACE B2W' },
  { value: 6, label: 'MARKETPLACE CNOVA' },
  { value: 7, label: 'VTEX' },
  { value: 8, label: 'GOL ACESSORIO' },
  { value: 9, label: 'GOL ORÇAMENTO TROCA' },
  { value: 10, label: 'GOL ORÇAMENTO CONSERTO' },
  { value: 11, label: 'MERCADO LIVRE' },
  { value: 12, label: 'MERCADO LIVRE' },
  { value: 14, label: 'EXPRESS' },
  { value: 15, label: 'EXTRAVIO VTEX MULTILASER' },
  { value: 16, label: 'EXTRAVIO B2W MULTILASER' },
  { value: 17, label: 'EXTRAVIO CNOVA MULTILASER' },
  { value: 18, label: 'EXTRAVIO MERCADO LIVRE MULTILASER' },
  { value: 19, label: 'EXTRAVIO GOL MULTILASER' },
  { value: 20, label: 'MARKETPLACE DOTZ' },
  { value: 21, label: 'MULTIHUB' },
  { value: 22, label: 'MULTIHUB - DROP SHIPPING' },
  { value: 23, label: 'CROSSDOCKING' },
  { value: 24, label: 'GOL DIRETO' },
  { value: 25, label: 'VTEX MULTILASER LOJA 01' },
  { value: 26, label: 'VTEX MULTILASER LOJA 01 - DROP' },
  { value: 27, label: 'B2B MARTINS' },
  { value: 28, label: 'MAX - TROCA FÁBRICA' },
  { value: 29, label: 'MAX - CONSERTO' },
  { value: 30, label: 'MAX - TROCA EXPRESSA' },
  { value: 31, label: 'MAX - ENVIO PRODUTO BONIFICADO' },
  { value: 32, label: 'FULFILLMENT' },
  { value: 33, label: 'MAX Coletas' },
  { value: 34, label: 'MAX Assist' },
  { value: 35, label: 'MANUAL - DIRETO NO ERP' },
  { value: 36, label: 'FULFILLMENT NERUS' },
  { value: 38, label: 'M2C Inside Sales' },
]

export const statusOptions = [
  { value: 'CREATED', label: 'Criado' },
  { value: 'VIEWED', label: 'Visualizado' },
  { value: 'PENDING', label: 'Pendente' },
  { value: 'AUTHORIZED', label: 'Autorizado' },
  { value: 'CONFIRMED', label: 'Confirmado' },
  { value: 'MANUAL_CONFIRMED', label: 'Confirmado Manual' },
  { value: 'DETECTION', label: 'Detectado' },
  { value: 'RECOVERY', label: 'Recuperação' },
  { value: 'CANCELED', label: 'Cancelado' },
  { value: 'DENIED', label: 'Negado' },
  { value: 'REFUNDED', label: 'Estornado' },
  { value: 'EXPIRED', label: 'Expirado' },
  { value: 'CHARGED_BACK', label: 'Contestado' },
]

export const companyOptions = [
  { value: 'Multilaser', label: 'Multilaser (1)' },
  { value: 'Multicomponentes', label: 'Multicomponentes (9)' },
  { value: 'Giga', label: 'Giga (20)' },
  { value: 'Giga 2', label: 'Giga 2 (22)' },
  { value: 'Watts', label: 'Watts (25)' },
]
